[workspace]

[package]
name = "plugin-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
pi-rust-plugin-protocol = { path = "../../crates/pi-rust-plugin-protocol" }
pi-rust-plugins = { path = "../../crates/pi-rust-plugins" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
pi-rust-plugin-host = { path = "../../crates/pi-rust-plugin-host" }
tempfile = "3.19.0"
